spring:
  application:
  boot:
    admin:
      discovery:
        ignored-services: consul
      ui:
        brand: '<img src="logo-glic.png"><span>Glic-Gateway Monitor</span>'
        title: 'Glic-Gateway Monitor'
        favicon: 'favicon.png'
      notify:
        mail:
          enabled: true
          to: mauricio.fenoglio@glic-solutions.com
          from: no-reply@glic-solutions.com
  mail:
    host: smtp.gmail.com
    port: 587
    username: no-reply@glic-solutions.com
    password: 'e3232FDFASX"#"!"#"%%%%%""!!!23232'
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    test-connection: false
server:
  port: 8888
  error:
    include-stacktrace: never
    include-exception: false
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        exclude: ['heapdump']
        include: '*'