spring:
  application:
    name: auth-jwt
    jwtSecret: glic-ms-jwt
    jwtExpirationInMs: 18000000
    jwtExcludePath: /**/auth/login,/**/annon/**,/actuator/**,/favicon.ico
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    platform: POSTGRESQL
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc.lob.non_contextual_creation: true
server:
  port: 8180
logging:
  level:
    org:
      hibernate:
        type: info
management:
  endpoints:
    web:
      exposure:
        exclude: ['heapdump']
        include: '*'