spring:
  application:
    jwtSecret: glic-ms-jwt
    jwtExpirationInMs: 18000000
    jwtExcludePath: /**/auth/login,/**/auth/sendRecovery/**,/**/auth/activate,/**/auth/recovery,/**/annon/**,/actuator/**,/favicon.ico
    activeEmail: true
    fromAddress: no-reply@glic-solutions.com
    emailBaseLink: http://payment.glic-solutions.com:8380
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5643/jwtauth
    username: postgres
    password: "Re$$$..123@"
    platform: POSTGRESQL
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: no-reply@glic-solutions.com
    password: 'e3232FDFASX"#"!"#"%%%%%""!!!23232'
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    test-connection: false
server:
  port: 8180
  error:
    include-stacktrace: never
    include-exception: false
logging:
  level:
    org:
      hibernate:
        type: info
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        exclude: ['heapdump']
        include: '*'
